### ISSUE TITLE
No hover or active styles on the sidebar channel list

### ISSUE THREAD

**Issue by pbaity** [pbaity/rocketchat-dark-mode#107]
**Describe the bug**
Previously (and still in light mode) when you hover or select a channel or direct message, it is highlighted in some way.

**To Reproduce**
1. Hover over any of the channels or direct messages in the sidebar
2. See that there is no hover or active style (without dark mode, there is)

**Expected behavior**
There should be hover and active highlighting as there is in light mode.

**Screenshots**

With highlighting in light mode (from top to bottom, no hover, active, and hovering):
![image](https://user-images.githubusercontent.com/39106297/104453949-2ed14a00-5573-11eb-9dac-b1bdce175c44.png)

Same setup but with dark mode:
![image](https://user-images.githubusercontent.com/39106297/104454118-5d4f2500-5573-11eb-9fbf-ae6085f3aa4e.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Browser: using Rocket.Chat desktop app
 - Version: server 3.9.3

**Comment by bkraul** [comment]
Make sure you are using the latest version of the script and CSS. This works with current master:

![y4AipWZ7LS](https://user-images.githubusercontent.com/14616851/104952199-a5ae7e80-5989-11eb-8160-3795cfb72b3a.gif)

**Comment by iamjameswalters** [comment]
@bkraul on what version? I can confirm @pbaity 's bug, but as he said, we're on 3.9.3.

**Comment by diggamies** [comment]
> @bkraul on what version? I can confirm @pbaity 's bug, but as he said, we're on 3.9.3.

Same here, still got the issue, even with the newest version of master.

**Comment by bkraul** [comment]
Running 3.11-develop here. Let me spin up 3.9.3 and will get back with you.

**Comment by bkraul** [comment]
So I can confirm this behavior on 3.9.3 all the way latest develop (3.11). My suspicion would be that CSS changes introduced after my initial 3.8 PR started touching the sidebar. Initially I had opted for not touching the sidebar at all because there were a lot of style conflicts. This no longer seems to be the case.

After doing a compare of what I have that works and the current master, my suspicion is that this is what is breaking it (on line 369):

**Comment by bkraul** [comment]
I just removed the mentioned block from my test instance, and the hover behaviors are working:
![pkwxUxkF7g](https://user-images.githubusercontent.com/14616851/105178906-428a2c80-5aee-11eb-856b-a234dcee2ce9.gif)

**Comment by pbaity** [comment]
This has since been resolved
