### ISSUE TITLE
Online badge icon not visible in direct chat

### ISSUE THREAD

**Issue by mbu147** [pbaity/rocketchat-dark-mode#114]
**Describe the bug**
Looks like in latest RocketChat Server 3.11.0 the online badge icon is not visible in direct chat window.

**To Reproduce**
1. Open any directchat
2. Look at the top in front of complete name, there's no online badge icon

**Screenshots**
Active Darkmode
![image](https://user-images.githubusercontent.com/36038279/106423801-6ab84a80-6461-11eb-8a30-5f0e37b70fa9.png)

Active Lightmode
![image](https://user-images.githubusercontent.com/36038279/106423836-7b68c080-6461-11eb-839f-893cbd44444a.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.1
 - Browser: Google Chrome 88.0.4324.9
 - RocketChat Server Version: 3.11.0
 - RocketChat Client Version: 3.1.1

**Additional context**
Offline Badge is visible :)
![image](https://user-images.githubusercontent.com/36038279/106424020-cb478780-6461-11eb-8ced-6360d71b0423.png)

**Comment by redzonej** [comment]
@mbu147 @pbaity I have the same issue with latest snap server version 3.10.5 and latest css.

Also, custom user statuses no longer show up underneath their name in Direct Message. Do you see this behavior as well?

**Comment by TBG-FR** [comment]
Can you reproduce it in RocketChat 3.11.x with the latest commits from this repo ? I just tried, and it seems fixed

If you really need this fixed for 3.10.x, I think you'll easily find the culprit: a `background-color` instruction is hiding the icon, overriding the `background` instruction of `.rcx-status-bullet-online`

**Comment by mbu147** [comment]
@TBG-FR 
yep - fixed for me with current RocketChat release (3.11.1) and master branch.

Thanks!
