### ISSUE TITLE
Color of cited messages

### ISSUE THREAD

**Issue by stbc** [pbaity/rocketchat-dark-mode#121]
**Describe the bug**
The color of cited message is not rendered in dark mode

**To Reproduce**
1. Cite a message
2. switch to dark mode

**Expected behavior**

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2520567/109128028-59f0b100-774f-11eb-8a40-0f936bafb35f.png)

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Firefox
 - Version 85

**Comment by araujorm** [comment]
I can confirm, both in Firefox and Rocket Chat client.

Also, when citing, the cited message is not visible. These issues are easily reproducible (just quote a message when using dark theme).
