### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by mmgoilf** [pbaity/rocketchat-dark-mode#124]

**Comment by fdellwing** [comment]
Are you sure that you reported that in in correct repository? This theme does not touch the symbols and definitely has to impact on file upload to the server.

**Comment by mmgoilf** [comment]
> 
> 
> Are you sure that you reported that in correct repository? This theme does not touch the symbols and definitely has to impact on file upload to the server.

Yea my bad was super sleep deprived when I made this, whoops. Just delete it.
