### ISSUE TITLE
Ugly white lines and bad thread height when in wide mode in 3.12.1

### ISSUE THREAD

**Issue by dusatvoj** [pbaity/rocketchat-dark-mode#128]
**Describe the bug**
Hi, I've recently upgraded to RC `v3.12.1` and RC-dark-mode to the code from master branch and I have some ugly white lines and bad height of wide thread window there

**To Reproduce**
1. Install RC 3.12.1
2. Apply dark mode
3. 
![image](https://user-images.githubusercontent.com/11560794/111393716-944bcf00-86b9-11eb-9512-450e21c28a85.png)
![image](https://user-images.githubusercontent.com/11560794/111394011-281d9b00-86ba-11eb-92c9-d9663d41f6d4.png)

**Expected behavior**
Pre 3.12 look (except some ugly white lines too)
![image](https://user-images.githubusercontent.com/11560794/111393791-be9d8c80-86b9-11eb-8e62-01e0d2c58993.png)

**Screenshots**
Above

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Latest desktop app
 - Version: `3.1.1-1` from AUR

**Additional context**
Any

**Comment by pbaity** [comment]
I'll work on the white lines, but I don't think the dark mode is causing the change in the height of the thread window.

**Comment by pbaity** [comment]
@dusatvoj Added a fix for this in #136, check it out and let me know what you think.

**Comment by dusatvoj** [comment]
@pbaity Looks much better. There's last white line in the middle and It will be excelently fixed. :hearts: 
![image](https://user-images.githubusercontent.com/11560794/115588080-a6c7b280-a2ce-11eb-83ee-eb0152fce9fe.png)

**Comment by pbaity** [comment]
Interesting, I don't see that white line on the side of the thread panel - in the picture I posted in that PR of the thread panel it's not there, and I still don't see it.

**Comment by dusatvoj** [comment]
Interesting. Nevermind :grinning:
Thank you for PR.
