### ISSUE TITLE
Can I change the color of the left pane to dark?

### ISSUE THREAD

**Issue by jseong309** [pbaity/rocketchat-dark-mode#13]
I wanted to see if there is a way I can change the panel that shows the channels and direct messages to be the same color as the conversation background?
By the way, thank you for this. LOVE that the user now has the option to switch between the dark mode and regular.
<img width="881" alt="RC Dark Theme" src="https://user-images.githubusercontent.com/39973530/74909989-4f4a5180-536e-11ea-8cdc-e205ed36d607.png">

**Comment by ankar84** [comment]
Hi, @jseong309 
Did you [properly installed](https://github.com/pbaity/rocketchat-dark-mode#installation) Dark mode?
In my case I see this:
![image](https://user-images.githubusercontent.com/4023037/74929973-ae02e000-53ed-11ea-8617-a1bb55211d16.png)

**Comment by pbaity** [comment]
@jseong309 Like @ankar84 mentioned, make sure you've got the dark mode installed properly first. Also make sure you restart Rocket.Chat to see the changes. If you've done that, let me know what version of Rocket.Chat you're using (you can find this by going to **About Rocket.Chat** in the menu) and whether you're using the desktop app or the browser.

**Comment by jseong309** [comment]
> @jseong309 Like @ankar84 mentioned, make sure you've got the dark mode installed properly first. Also make sure you restart Rocket.Chat to see the changes. If you've done that, let me know what version of Rocket.Chat you're using (you can find this by going to **About Rocket.Chat** in the menu) and whether you're using the desktop app or the browser.

I am pretty sure I installed this correctly.
1. Copy and Paste CSS file in Custom CSS. (Also, tried to reset, save, then pasted css file, save)
2. Copy and Paste JS file in Custom Script for Logged In Users. (Also, tried to reset, save, then pasted js file, save)

Is there another step I am missing?

Still same result on Windows(2.17.7) and Web browser.

Ubuntu 16
Apache
Snap Install 2.4.9
<img width="888" alt="RC Version" src="https://user-images.githubusercontent.com/39973530/74949374-8c383780-53b2-11ea-8a22-98962838cd64.png">
<img width="829" alt="RC CSS" src="https://user-images.githubusercontent.com/39973530/74949843-21d3c700-53b3-11ea-9467-57bde61b3a48.png">
<img width="837" alt="RC JS" src="https://user-images.githubusercontent.com/39973530/74949846-24362100-53b3-11ea-8cd9-5cc30ad03191.png">

**Comment by ankar84** [comment]
@jseong309 as you can see left pane in Administration area has a proper color.

**Comment by jseong309** [comment]
So I figured it out. One of the lines I changed from color-gray-lightest to color-dark-medium.
And that fixed it. =)

<img width="451" alt="RC CSS Darktheme" src="https://user-images.githubusercontent.com/39973530/75009340-48374800-542f-11ea-87b3-b8ebf9850db5.png">
<img width="591" alt="RC Dark working" src="https://user-images.githubusercontent.com/39973530/75009445-8f253d80-542f-11ea-8a27-29c0c5d0cdad.png">

**Comment by pbaity** [comment]
@jseong309 `--rc-color-primary` and `--rc-color-primary-lightest` were set to those values when I forked this project, so I'll have to see where they're used to see if they ought to be changed. 

I suspect maybe this is an issue with Rocket.Chat 2.17.7, since I'm not seeing the problem on 2.16.0, but I noticed the `<aside>` with class `sidebar` has a background color set to `--sidebar-background`. Instead of changing `--rc-color-primary` (since I'm not sure what else that would impact) try adding this rule: `--sidebar-color: var(--color-dark);` and see if that fixes the issue (it works for me in 2.16.0)

**Comment by pbaity** [comment]
@jseong309 I've opened PR https://github.com/pbaity/rocketchat-dark-mode/pull/20 to fix this and other issues. Give the code in that PR a try and let me know if it fixes it for you!

**Comment by jseong309** [comment]
@pbaity That fixed the issue! Only thing is when I hover over the dark/light mode icon it says undefined. But I do like that the fonts are more visible on the lighter backgrounds.

**Comment by pbaity** [comment]
@jseong309 If you could, open your console in Rocket.Chat and run `defaultUserLanguage()` and tell me what it returns. I'll make sure to fix that so it won't say undefined. Also, let me know what the label should say in your user language!
