### ISSUE TITLE
Hover in options list is to bright - server version 3.13.0

### ISSUE THREAD

**Issue by emikolajczak** [pbaity/rocketchat-dark-mode#131]
**Describe the bug**
I.e. in room options menu, hoover items are too bright. Example on screen below

**To Reproduce**
1. Go to any room
2. Click three dots (more options)
3. move pointer on any options
4. Hover is too bright

**Expected behavior**
Hover is darker

**Screenshots**

![image](https://user-images.githubusercontent.com/50440047/113844303-a12d8100-9794-11eb-9a6f-a27aa0d00f60.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser All
 - Version All

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fdellwing** [comment]
I'm currently looking into this issue. I can reproduce the white border around the menu, but not the white highlight. Did you modify some colors in the custom CSS or in RC itself (`Layout -> Colors`)?

**Comment by emikolajczak** [comment]
Hi, I didn't change `Colors`, only custom CSS.

**Comment by fdellwing** [comment]
Can you provide me your currently used custom CSS so that I can take a look what might be the problem?

**Comment by emikolajczak** [comment]
Strange, i have double check after my server restart and now it looks ok. As you said, only white border around three dots menu. Sorry for false alarm, it looks as some cache on my side.

**Comment by fdellwing** [comment]
No problem 👍

**Comment by pbaity** [comment]
@emikolajczak Added a fix for this in #136, check it out and let me know what you think.
