### ISSUE TITLE
Dark/Light toggle button is too small - 3.13.0

### ISSUE THREAD

**Issue by emikolajczak** [pbaity/rocketchat-dark-mode#132]
**Describe the bug**
After upgrade Rocket.Chat server to 3.13.0 toggle button is too small.

**To Reproduce**
1. Upgrade server to 3.13.0
2. Check toggle button size
3. Toggle button is too small

**Expected behavior**
Toggle button has correct size

**Screenshots**
![image](https://user-images.githubusercontent.com/50440047/113855818-c32d0080-97a0-11eb-91d7-66936a387dbb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser All
 - Version All

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fdellwing** [comment]
I'm looking into this issue, but I can not reproduce it. Can anyone here reproduce the problem?

**Comment by pbaity** [comment]
I also don't see this. @emikolajczak has this issue persisted for you, even after refreshing your cache?

**Comment by pbaity** [comment]
@emikolajczak Haven't heard back and still don't see this issue. If it persists you can comment here or open a new issue.
