### ISSUE TITLE
No switch button after apply css and js

### ISSUE THREAD

**Issue by itJunky** [pbaity/rocketchat-dark-mode#133]
First i set it in version 3.12.0. Because i don't see any special version of dark-mode for it. Afer that i clean browser data(not cookies).
No switch button for dark-mode at top of left menu.
Next, i'll update rocket to 3.13.0 version and check custom CSS and custom script fields. Not empty and correct text, but no switch again :(
After that i'll change deafault in js to const darkModeDefault = true;
And nothing changes in interface too :(

No errors in F12 console. How can i debug and fix it?

**Comment by fdellwing** [comment]
Did you make sure you pasted the script into `Custom Script for Logged in Users`? It's the third field from top.

**Comment by itJunky** [comment]
Yes, beacuse i see only one "Custom scripts" field.
![изображение](https://user-images.githubusercontent.com/1845772/114148387-5c375500-9922-11eb-9ba3-968a60cc78c6.png)

**Comment by fdellwing** [comment]
Click on custom scripts and there will be 3 text fields.

**Comment by pbaity** [comment]
@Blueshawk the buttons are actually [SVGs](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js#L15-L20), not PNGs, so no need to have them on your server.

**Comment by Blueshawk** [comment]
Got it sorted now thanks. I actually did something silly and didn't catch it till just now, so sharing. I usually clone stuff from git so when I decided to just grab the two files instead I didn't realize I got the html page.. (facepalm) Kudos to rocketchat for not exploding when fed huge amounts of garbage. LOL 

@itJunky Check to be sure your script is actually what you think it is.

**Comment by itJunky** [comment]
> Click on custom scripts and there will be 3 text fields.

Wow, thanks. I set code to first field, but need set it to third field. It's because i see translated to russian language field names. Before i think it just different after translation.

Now it's worked.
