### ISSUE TITLE
No scroll bar in channel list after switching between light- and dark mode

### ISSUE THREAD

**Issue by sennewood** [pbaity/rocketchat-dark-mode#135]
**Describe the bug**
The scroll bar disappears when you switch between light and dark mode.

**To Reproduce**
1. Move mouse out of Rocket.Chat (i.e. to the browser title bar) and keep it there.
2. Refresh the page.
3. Switch to light mode.
4. Refresh the page.
5. Switch to dark mode.
6. Move mouse to the channel list.
7. No scroll bar.

**Expected behavior**
There should be a scroll bar.

**Screenshots**
No.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: 87

**Smartphone (please complete the following information):**
 - Device: -/-
 - OS: -/-
 - Browser -/-
 - Version -/-

**Additional context**

- Rocket.Chat: 3.13.2

**Comment by pbaity** [comment]
Is anyone else able to recreate this issue? I was not, but I'm on Mac.

**Comment by fdellwing** [comment]
I can not confirm the issue that is mentioned here, but I have a different problem:

The scrollbar (a pretty dark grey) auto hides some seconds after the mouse leaves the channel list. With the steps mentioned above I do get a second scrollbar in a lighter color that is not automatically hidden.

**Comment by sennewood** [comment]
Maybe it's important to know, that I use my work laptop, so I only use the touchpad and don't have a mouse wheel - I can only scroll with those tiny scroll bars ^^

**Comment by fdellwing** [comment]
It's a bit off topic, but on 99% of modern laptops + OS you can enable two-finger scrolling for your touchpad.

**Comment by pbaity** [comment]
@sennewood Is this issue still occurring for you?

**Comment by pbaity** [comment]
Closing as stale
