### ISSUE TITLE
Rocket.Chat 3.14.0 - CSS/JS doesn't appear to load?

### ISSUE THREAD

**Issue by philliml74** [pbaity/rocketchat-dark-mode#137]
**Describe the bug**
CSS and JS do not appear to be working in 3.14.0

**To Reproduce**
1. Goto Administration
2. Goto Layout
3. Open Custom CSS
4. Paste CSS from 'master' branch
5. Open Custom Script
6. Paste JS from 'master' branch

**Expected behavior**
The toggle image to appear after a refresh and clear of browser cache.

**Screenshots**
![image](https://user-images.githubusercontent.com/5111693/117374065-766d4000-ae9a-11eb-9192-19ebaf3b381b.png)
![image](https://user-images.githubusercontent.com/5111693/117374091-82f19880-ae9a-11eb-88c6-be4cd736206d.png)
![image](https://user-images.githubusercontent.com/5111693/117374130-956bd200-ae9a-11eb-9e52-2de089e7ba09.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 
 - Version 88.0 (64-bit)

 - Browser Rocket.Chat Application
 - Version 3.1.1

**Smartphone (please complete the following information):**

**Additional context**
running a docker version of rocket.chat via https://docs.rocket.chat/installation/docker-containers/docker-compose

Version
3.14.0
Apps Engine Version
1.25.0
Node Version
v12.22.1
Database Migration
222 (May 6, 2021 6:30 PM)
MongoDB
4.0.24 / mmapv1 (oplog Enabled)
Commit Details
HEAD: (1255c8f0c)
Branch: HEAD

**Comment by fdellwing** [comment]
It seems like you pasted the script in the wrong area (`Custom Script for Logout Flow`). It has to go into `Custom Script for Logged in Users`.

**Comment by philliml74** [comment]
Well, um, well...thank you for pointing that out.  I have corrected that and now it just works.
