### ISSUE TITLE
Multiple Dark mode icons appears

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#14]
**Describe the bug**
Multiple Dark mode icons appears

**To Reproduce**
I know for sure when you **edit dark-mode-toggle.js** in **Custom Scripts > Custom Script for Logged In Users** this happens.
But now I didn't edit anything, but have a lot of icons
**CTRL+R** in desktop client or **F5** in browser version fix the problem for a time

**Expected behavior**
**Only one Dark mode icon should remain all the time.**

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/75006602-58791280-5483-11ea-963e-a2e89c3f3ecb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 2.17.3

**Comment by pbaity** [comment]
@ankar84 Around [line 48 in dark-mode-toggle.js](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js#L48), the script is supposed to detect if the dark mode button is already visible and stop if it is:
```javascript
// do nothing if button is already on the screen
if (darkModeButton.is(':visible')) {
    return;
}
```
My guess is that the button isn't getting counted as visible for one reason or another.

**Comment by ankar84** [comment]
> My guess is that the button isn't getting counted as visible for one reason or another.

Could it be if I changed (translated to Russian) two lines:
https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js#L17
https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js#L46

I changed **Toggle Dark Mode** to **Смена оформления**

**Comment by pbaity** [comment]
@ankar84 I tried changing the label text to **Смена оформления** on my instance and it didn't cause any issues for me. Even when I edit the script in the Admin panel, I can't reproduce (using Mac) on Chrome, Firefox, or desktop app. I'm thinking a possible solution may be to write some code in the script that finds and removes the button if it exists before adding it.

As an aside, take a look at [this PR](https://github.com/pbaity/rocketchat-dark-mode/pull/18) and let me know what you think.

**Comment by ankar84** [comment]
After #19 I did not see multiple icons anymore.
I don't if it helped or something else, but result is good.
