### ISSUE TITLE
Variants not visible in Poll application and something not visible in prune menu

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#141]
**Describe the bug**
When you install Rocket.Chat Poll application and create some poll - you can't see variants in dark mode

**To Reproduce**
1. Install Poll App
2. Create poll
3. Chech variants

**Expected behavior**
All variants should be visible

**Screenshots**
Pool issue
![image](https://user-images.githubusercontent.com/4023037/118929435-2d62c480-b94d-11eb-994c-700d23530e98.png)
![image](https://user-images.githubusercontent.com/4023037/118929471-3c497700-b94d-11eb-94d5-a83193b94190.png)

Prune menu
![image](https://user-images.githubusercontent.com/4023037/118929616-6bf87f00-b94d-11eb-819d-f6ac1a164e40.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 90

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ankar84** [comment]
I guess in my case that code will fix Poll App issue

```
/***** Poll App *****/
body.dark-mode [data-username="app.poll"] .rcx-css-erwtrf {
	color: var(--color-white) !important; 
}
```

Important that in my case `data-username="app.poll"` but in dark-mode.css is `data-username="poll.bot"` for some reason

**Comment by pbaity** [comment]
Interesting, @ankar84 what version of Rocket.Chat are you using? `data-username="poll.bot"` works for me but not `data-username="app.poll"` on RC 3.13.2.

`data-username="poll.bot"`

![image](https://user-images.githubusercontent.com/39106297/119004122-46bf3d00-b95c-11eb-9d32-d64d76f3d1b1.png)

`data-username="app.poll"`

![image](https://user-images.githubusercontent.com/39106297/119003973-268f7e00-b95c-11eb-84ce-df58cdae2fdf.png)

**Comment by ankar84** [comment]
> Interesting, @ankar84 what version of Rocket.Chat are you using?

3.14


> `data-username="poll.bot"` works for me but not `data-username="app.poll"` on RC 3.13.2.
> 
> `data-username="poll.bot"`
> 
> ![image](https://user-images.githubusercontent.com/39106297/119004122-46bf3d00-b95c-11eb-9d32-d64d76f3d1b1.png)
> 
> `data-username="app.poll"`
> 
> ![image](https://user-images.githubusercontent.com/39106297/119003973-268f7e00-b95c-11eb-84ce-df58cdae2fdf.png)
> 
>

**Comment by pbaity** [comment]
Got it. Based on that see my suggestion here: https://github.com/pbaity/rocketchat-dark-mode/pull/142/files#r636205362

**Comment by ankar84** [comment]
Poll issue fixed by https://github.com/pbaity/rocketchat-dark-mode/pull/142
