### ISSUE TITLE
Users that Reacted modal window need to be more clear

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#143]
**Describe the bug**
**Users that Reacted** modal window need more consistent background 

**To Reproduce**
1. Set reaction to message
2. Open Reaction in message menu
3. Check modal window

**Expected behavior**
Consistent background

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/118952551-b802ee00-b964-11eb-8c60-e89acd3d383c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 90

**Comment by ankar84** [comment]
That https://github.com/RocketChat/Rocket.Chat/pull/22752 could lead to fix

**Comment by pbaity** [comment]
Seems to be resolved as of 3.18.1
