### ISSUE TITLE
Video Conference modal - Cancel button not visible

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#144]
**Describe the bug**
**Cancel** button not visible at **Video Conference** modal

**To Reproduce**
1. Click call button
2. Check **Video Conference** modal

**Expected behavior**
Cancel should be readable

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/118963160-d968d780-b96e-11eb-8780-f662c714aca4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 90

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
I'm having this issue also.

**Comment by TBG-FR** [comment]
Should be fixed in #162 ;)

I don't understand why some modal cancel buttons have `.rcx-button--ghost` and some other don't... If they all had it, this issue wouldn't be existing ! (maybe we should report that to RocketChat team/repo, it looks like a consistency issue)

**Comment by pbaity** [comment]
Fixed in #162
