### ISSUE TITLE
Dark Mode button not appearing in 3.16.0

### ISSUE THREAD

**Issue by tammer123** [pbaity/rocketchat-dark-mode#149]
**Describe the bug**
Hello, after updating from 3.14.1 -> 3.16.0, I don't have the dark mode button appearing. I even tried to remove the custom css and script, still didn't help.

**To Reproduce**
1. Goto Administration
2. Goto Layout
3. Open Custom CSS
4. Paste CSS from 'master' branch
5. Open Custom Script
6. Paste JS from 'master' branch

**Expected behavior**
The toggle image to appear after a refresh and clear of browser cache.

**Screenshots**
![dark1](https://user-images.githubusercontent.com/12547142/124244939-258b6800-db28-11eb-8360-792d5cf64de8.PNG)
![dark2](https://user-images.githubusercontent.com/12547142/124244952-28865880-db28-11eb-9bb8-27952b69ca6d.PNG)
![dark3](https://user-images.githubusercontent.com/12547142/124244968-2c19df80-db28-11eb-846c-eac0f3a60372.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Rocket.Chat App and all Browsers
 - Version : App 3.2.2 and Browsers latest

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser : Any
 - Version: Rocket.Chat server 3.16.0

**Additional context**
Running Rocket.Chat server from tar download not in Docker.

**Comment by tammer123** [comment]
Hello,

I found the issue.

After adding the custom script part of the dark mode, script.js is not generated till the end and brakes. If I remove the darkmode script, then script.js generates till the end.

Is the error on my end or something else?

**Comment by ankar84** [comment]
Working good in my deployment with 3.16.3

**Comment by tammer123** [comment]
![image](https://user-images.githubusercontent.com/12547142/126313174-48b3bce1-f5c7-419a-b805-0ba8deee0064.png)

**Comment by pbaity** [comment]
@tammer123 Sorry I haven't answered yet, but I haven't had this issue. I have no idea why the script is getting truncated in your instance. Try copying over the most recent [dark-mode-toggle.js](https://github.com/pbaity/rocketchat-dark-mode/blob/master/dark-mode-toggle.js) (the one in the screenshot above is outdated), but it looks like the code getting truncated isn't related to dark mode, so I can't help there (everything below the comment `//Custom_Script_On_Logout`).
