### ISSUE TITLE
notification for new version not working on dark theme

### ISSUE THREAD

**Issue by adipose** [pbaity/rocketchat-dark-mode#152]
When a new version of rocketchat comes out, a notification may pop up for administrators at the top of the window.  On the far right, an "X" appears to dismiss this notification.  Only, it doesn't show up in the dark theme, so you have to switch to light theme to dismiss it.  I'll send a screenshot next time it pops up.

**Comment by adipose** [comment]
Here's an example of the problem:

![image](https://user-images.githubusercontent.com/3324395/132560398-92b9d322-eff1-4e10-b0d4-cf79e8290db9.png)

In white mode:

![image](https://user-images.githubusercontent.com/3324395/132560523-2d3cd813-14b8-4653-b2f6-e49bc32dcd8f.png)

**Comment by pbaity** [comment]
Closed by #154
