### ISSUE TITLE
Admin page pagination color

### ISSUE THREAD

**Issue by beloniki** [pbaity/rocketchat-dark-mode#153]
Hi there.

I'm glad to use this one. One little bug, that I've found is on the administration panel: the selected page numbers are not readable in a dark mode.

My solution is to add a rule for this class into css text:

```
...
/************** Admin panel & Account panel ******************/

.page-list a:not(.rc-button), .page-settings a:not(.rc-button) {
	color: var(--primary-font-color);
}

/**** Addition start ****/
body.dark-mode .rcx-pagination__link:disabled {
  color: var(--color-white);
}
/**** Addition end ****/

/*body.dark-mode .simplebar-content > .rcx-box => will also modify sidebar background */
body.dark-mode .simplebar-content > .rcx-css-fr02gd { /* main content */
    background-color: var(--color-dark);
}
...
```

Be well! :)

**Comment by pbaity** [comment]
Hi @beloniki , so sorry for the long delay! I added this code but didn't notice a difference, can you share a screenshot? (if this is still relevant; maybe the issue was otherwise fixed since you opened this)
