### ISSUE TITLE
Issue: Dark Mode not applied in embedded mode

### ISSUE THREAD

**Issue by jrgong420** [pbaity/rocketchat-dark-mode#158]
Hey guys

When the chat is opened via URL with the parameter `?layout=embedded`, the dark mode is not applied. We successfully reproduced the issue on Chrome on MacOS as well as on Android.

Is there any way to enable Dark Mode in embedded layout?

**Comment by pbaity** [comment]
This has been added in #163 by @TBG-FR.  For this to work, enable the top navbar in the embedded layout by going to "Administration -> Layout -> Interface -> Show top navbar in embedded layout". You'll now get the dark mode button in the top navbar.
