### ISSUE TITLE
Rocket.Chat 4.3.0

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [pbaity/rocketchat-dark-mode#161]
Rocket.Chat 4.3.0 is out, some elements of the script need to be updated to accommodate the new changes.
- Message options menu (three dots) text is unreadable on hover
- Account menu (clicking account icon)
- Message Info "OK" button
- Video Conference “Cancel” button
- 2FA backup code box after enabling 2FA
- Likely more I have missed.

**Comment by TBG-FR** [comment]
I started working on 4.3.0 modifications to update the dark mode, here are some elements : 

- Message options menu -> fixed
- Account menu -> unable to see the issue, can you provide a screenshot ?
- Message info OK button -> same as above
- Video Conference "Cancel" button -> RC issue, this button is missing `rcx-button--ghost` class (**should we open a PR ?**)
- 2FA -> not tester yet
- I found some other elements, I'll update this asap

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
Account menu:
<img width="198" alt="1" src="https://user-images.githubusercontent.com/76442625/148595556-67dbc32e-4c71-4437-b7ab-e49dee95ef97.PNG">

Message info OK button:
![2](https://user-images.githubusercontent.com/76442625/148595571-0033cd86-c927-4553-8544-ab85e26e9e88.PNG)

**Comment by pbaity** [comment]
These issues were fixed in #162 . If you find any other specific problems, feel free to open new issues for those.

**Comment by TBG-FR** [comment]
@ae5960e8-a6fc-491f-b252-898ecf59af95 Can you check if "Message info OK button" is fixed ? If not, where should I go to display that popup/modal ?
