### ISSUE TITLE
Account name in status menu unreadable

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [pbaity/rocketchat-dark-mode#165]
Previously, I had suggested changing the background of this element from white to dark, to match the dark theme, however this has resulted in the user's account name in the status menu becoming unreadable.
![sss](https://user-images.githubusercontent.com/76442625/148821204-fea4c65f-a4c1-41ed-8a6d-ccf9207537d9.PNG)

Secondly, I'm now of the opinion that white was more readable and appropriate than the new colour. I think this change should be reverted, or, instead, it could use a dark colour which does not match the background on which is hovers above to improve readability.

**Comment by TBG-FR** [comment]
My bad, I didn't see this one !

I also tried a dark "lighter" color, thinking it was better, but I changed my mind because in normal/light mode, Rocket Chat uses one color for the sidebar, and one color for the main chat panel **and** menus

I'll show you some screenshots so everyone can decide which one is better

**Comment by TBG-FR** [comment]
Here's RocketChat original colors

![RC_Menu_Original](https://user-images.githubusercontent.com/18146038/148830172-51ad3efc-d3ae-40db-8dd7-494331746bb8.png)

And here's what I did in #162

![RC_Menu_Dark](https://user-images.githubusercontent.com/18146038/148830254-989e02d9-803f-49d5-9526-a1b570fc3bb5.png)

**Comment by TBG-FR** [comment]
One option could be to use `--color-dark-medium`

![RC_Menu_DarkMedium](https://user-images.githubusercontent.com/18146038/148830302-91eac913-40ad-46e7-ac25-242670e34031.png)

**Comment by TBG-FR** [comment]
Another option would be to use `--color-darkest`

![RC_Menu_Darkest](https://user-images.githubusercontent.com/18146038/148830341-82169aec-2184-4df7-9781-85aa6863a4d1.png)
