### ISSUE TITLE
Does not seem to work on 4.4.2

### ISSUE THREAD

**Issue by 3li0** [pbaity/rocketchat-dark-mode#170]
**Describe the bug**
Does not seem to work on latest version of RC 4.4.2

**To Reproduce**
Install scripts as instructed in layout "custom css" and "logged in users" custom script.

**Expected behavior**
Dark Mode Added to UI, however dark mode is not evident after saving changes via admin interface.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Agnostic - does not matter if you access the UI in Linux/Windows behavior is the same
 - Browser: Firefox/Vivaldi/Chrome
 - Version: Latest

**Comment by ae5960e8-a6fc-491f-b252-898ecf59af95** [comment]
It works with mine on the latest version, 4.4.2.

**Comment by saschafoerster** [comment]
Maybe you added the script in the wrong field? "Custom Script for Logged In Users", I did that one wrong in the beginning.

**Comment by pbaity** [comment]
@3li0 just to confirm, you did toggle dark mode on with the toggle switch here, correct?

![image](https://user-images.githubusercontent.com/39106297/155223342-171c972b-e53e-4006-91fe-9ef1cb0f76d3.png)

If so, please share some screenshots of what you mean. I'm on 4.4.2 and haven't found any major problems so far.

**Comment by pbaity** [comment]
@3li0 So far it seems like this is working for others on 4.4.2 (and we're fixing any small misc issues), so I'm closing this. But if you find it's still not working reach out to me via this issue and I can help you troubleshoot, just include some screenshots.
