### ISSUE TITLE
Message info box contains unreadable text

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [pbaity/rocketchat-dark-mode#172]
**Describe the bug**
Some of the text in the screenshot is unreadable.

**To Reproduce**
1. Open the Read by/Info menu of any message.
2. Hover cursor over any user read event.

Screenshot:
<img width="452" alt="Untitled-min" src="https://user-images.githubusercontent.com/76442625/155912995-59aceaa5-da0c-4acf-ba48-0084948a2863.png">

Thank you.

**Comment by pbaity** [comment]
Should be fixed by #171 but for some reason I personally don't have a message info or "read by" option in my instance...? Not sure why but I trust @TBG-FR 's fix. If you find it's not fixed for you, please reopen.

**Comment by TBG-FR** [comment]
> Should be fixed by #171 but for some reason I personally don't have a message info or "read by" option in my instance...? Not sure why that is, but I trust @TBG-FR 's fix. If you find it's not fixed for you, please reopen.

Yeah that feature is disabled by default, I had to go into settings (Admin > Message) and enable it to test it 😉

**Comment by pbaity** [comment]
Ah, now I've confirmed it myself too! Thanks @TBG-FR .
