### ISSUE TITLE
Room members list contains unreadable elements

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [pbaity/rocketchat-dark-mode#173]
**Describe the bug**
Some of the text and a button in the screenshot is unreadable.

**To Reproduce**
1. Open the Member list within any room.
2. Hover cursor over any room member account.

Screenshot:
<img width="271" alt="Untitledd-min" src="https://user-images.githubusercontent.com/76442625/155913016-c06d6587-4e11-4a0d-aaa7-f913b5056447.png">

Thank you.

**Comment by pbaity** [comment]
Fixed by #171
