### ISSUE TITLE
Wrong colour of "You have joined a new direct message with" text

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [pbaity/rocketchat-dark-mode#177]
**Describe the bug**
The text “You have joined a new direct message with” when starting a new DM is difficult to read because of the colour of the text.

**To Reproduce**
1. Start a new DM or scroll to the beginning of an active DM.
2. The issue should be clear.

**Expected behavior**
The text is a more readable, lighter colour.

**Comment by TBG-FR** [comment]
You're right, the CSS selector has been modified, I'm working on a 4.8.1 version, it'll fix that

**Comment by pbaity** [comment]
Fixed by #185. If anybody sees the issue reoccur just reopen this issue!
