### ISSUE TITLE
Quotes have white border around them

### ISSUE THREAD

**Issue by acoolstraw** [pbaity/rocketchat-dark-mode#179]
**Describe the bug**
Quotes have a white border around them

**To Reproduce**
1. Quote someone's message

**Expected behavior**
No white border around it

**Screenshots**
![image](https://user-images.githubusercontent.com/45886986/164768602-41315a90-71c8-4a7a-b916-fea0aa312742.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - Version: 100

**Additional context**
I can't find which element the border is applied to

**Comment by TBG-FR** [comment]
I will check and try to remove it, but if I remember correctly I already tried months ago and this was the best result I could get

**Comment by TBG-FR** [comment]
Alright, I think I got it ! (PR is on its way 🤙 )

- Quote (regular) in dark-mode
![image](https://user-images.githubusercontent.com/18146038/174082940-3f0dc148-48c7-4306-a0b6-38b19a96b66a.png)

- Quote (focus/hover) in dark-mode
![image](https://user-images.githubusercontent.com/18146038/174083026-c56ddca3-f1a0-4d87-987e-92f21401fafa.png)

**Comment by pbaity** [comment]
Fixed by #185. If anybody sees the issue reoccur just reopen this issue!
