### ISSUE TITLE
Thread list broken in 4.8.1

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#180]
**Describe the bug**
Thread list is white in dark mode in 4.8.1 (could be broken earlier)

**To Reproduce**
1. Go to chat with threads
2. Open Thread list

**Expected behavior**
Thread list is dark in dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/173745760-7af4e8b5-34a9-4f4a-b45d-339705989ade.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 100
 
 **Additional context**

**Comment by TBG-FR** [comment]
Fix incoming 😄 

![image](https://user-images.githubusercontent.com/18146038/174101759-ef7824a7-0c07-4c0f-8cd3-7e3f5cb85c42.png)

**Comment by ankar84** [comment]
> Fix incoming 😄 
> 
> ![image](https://user-images.githubusercontent.com/18146038/174101759-ef7824a7-0c07-4c0f-8cd3-7e3f5cb85c42.png)
> 

Wow! Excellent job!!!

**Comment by pbaity** [comment]
Fixed by #185. If anybody sees the issue reoccur just reopen this issue!
