### ISSUE TITLE
Darkmode not working

### ISSUE THREAD

**Issue by JonnyBDev** [pbaity/rocketchat-dark-mode#187]
**Describe the bug**
Hey. I've just "installed" the darkmode as listed in the READ.ME. Copied the content of both files to their target location. Unfortunately there is no icon to toggle the mode. Restart (of the server container), reloading (CMD+F5), disable cache generally and different browsers did not solve the issue for me.

**To Reproduce**
1. "Install" the darkmode like mentioned in the READ.ME

**Expected behavior**
There should be a toggle-button in the upper-left bar to toggle the darkmode.

**Screenshots**
![image](https://user-images.githubusercontent.com/20868670/175920268-23e51ef2-0798-4a01-9190-f29e3b857d9d.png)
![image](https://user-images.githubusercontent.com/20868670/175920325-2a70a574-4087-46ac-9750-c5cdcef63cde.png)
![image](https://user-images.githubusercontent.com/20868670/175920587-3a3f388c-c36f-420b-8871-b3d29ac8fd59.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome, Safari
 - Version: latest

**Comment by JonnyBDev** [comment]
Nvm. Didn't setup the service so I forgot to check the version. Thought it was the latest - it wasn't.
Anyway a suggestion for the READ.ME. I was stupid and just copy pasted it without looking at the input fields at all. Copied the .js to the first input field. That was the error because it's for the logout flow. I should've pasted it in the 3rd field (for logged in users). Probably something you could add in the READ.ME for some more clearification. :) Thanks.

**Comment by pbaity** [comment]
Clarified in https://github.com/pbaity/rocketchat-dark-mode/commit/f262b76351e5731a2fa7487f44e14ce58ae532f6 for you!
