### ISSUE TITLE
Dark Mode not working right in RC5.0

### ISSUE THREAD

**Issue by D34DC3N73R** [pbaity/rocketchat-dark-mode#189]
**Describe the bug**
class names appear to have changed in RC 5.0

**To Reproduce**
1. Apply dark mode CSS in RC 5.0
2. Observe

**Expected behavior**
Dark mode works in RC 5.0

**Screenshots**
![image](https://user-images.githubusercontent.com/9123670/180629433-2f91dcda-30a0-4bf8-b48f-27d7c836ca86.png)

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser: Chrome + Desktop client
 - Version: RC V 5.0
 
**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Comment by ankar84** [comment]
@TBG-FR Hello! We need your help here!

**Comment by lpla** [comment]
MRW I opened Rocket Chat this morning:

![eyes](https://media.giphy.com/media/oS4bJ2sRXKVDa/giphy.gif)

**Comment by TBG-FR** [comment]
Will be working on that today or tomorrow 😉 Don't hesitate to check all (sub)menus and items to report them all !

**Comment by avpnusr** [comment]
Seems like nearly all things are normal - at least for my installation.

Only the messages in the chat-windows have a white background color and get (the right) grey color, while hovering over it.

Don't know if this helps, but in Dev-Tools I get this while selecting the element...

![image](https://user-images.githubusercontent.com/43516996/180983813-c9fd6384-2476-483e-b781-2474918812f5.png)

**Comment by ankar84** [comment]
> Don't hesitate to check all (sub)menus and items to report them all !

Discussion list in chat
![image](https://user-images.githubusercontent.com/4023037/180986106-8b5bd15d-a0a3-4222-934a-93e56e2ce1d5.png)
Call modal
![image](https://user-images.githubusercontent.com/4023037/180986173-ab9b8c3b-fcb6-4ba8-9605-405f58d53c35.png)
Admin UI - Info (Low contrast)
![image](https://user-images.githubusercontent.com/4023037/180986512-8970eed3-f099-47e4-a352-d9d5839e3013.png)
Admin UI - Users (Name not visible)
![image](https://user-images.githubusercontent.com/4023037/180986681-66618df1-e374-4d59-880e-3f69e1d83c3b.png)

Rest looks fine in general...



> Will be working on that today or tomorrow

Thank you so much for your effort!!!

**Comment by pbaity** [comment]
Not all heroes wear capes. @TBG-FR is the awesome!

**Comment by TBG-FR** [comment]
Eveything you reported @ankar84 should be fixed now, including Call modal

@here if you guys could try my modifications and report any missing things, that would be great ! 💪 

Thanks for all the kind words 🙇

**Comment by ankar84** [comment]
> Eveything you reported @ankar84 should be fixed now, including Call modal

You are fantastic, man!!!!

> @here if you guys could try my modifications and report any missing things, that would be great ! 💪

Already checking!

**Comment by pbaity** [comment]
This should be closed by #190 . Thanks so much to @TBG-FR 's amazing work there!

If anyone finds additional issues, please open a new issue with the details.
