### ISSUE TITLE
Improve Login Page When In Dark Mode

### ISSUE THREAD

**Issue by 4g7jegc** [pbaity/rocketchat-dark-mode#21]
**Describe the bug**
The login page doesn't look right when in dark mode. It looks fine in light mode. Forgot your password and Register a new account links are black text on dark gray background and barely visible. The login box is very dark gray on a bright gray almost white background. I think login page is missing css styles completely for dark mode.

**To Reproduce**
Go to rocketchat is browser. Be logged out. Change to dark mode. Click on a channel and then click login and its unstyled.

**Screenshots**
![wut](https://user-images.githubusercontent.com/61639362/75617582-9d0d4980-5b26-11ea-932b-d6464f220b68.jpg)

All browsers.

**Comment by pbaity** [comment]
@4g7jegc Thanks for catching this! Take a look at PR https://github.com/pbaity/rocketchat-dark-mode/pull/22 and try it out. Let me know if this fixes.

**Comment by pbaity** [comment]
@4g7jegc Closed by merging PR #22 . If this doesn't solve the problem, just reopen this issue.
