### ISSUE TITLE
Make borders darker

### ISSUE THREAD

**Issue by ddkedr** [pbaity/rocketchat-dark-mode#210]
**Describe the bug**
Inputs and button borders are too light

**To Reproduce**
It can be seen pretty much everywhere

**Expected behavior**
It would be nice of those border will be darker or ever transparent (depending on the object)

**Screenshots**
Here are a couple examples. Borders look off
<img width="323" alt="image" src="https://user-images.githubusercontent.com/46792476/214375943-10d05ac2-5cc7-4e8c-a5af-fbed6c6bdb86.png">
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/46792476/214376110-aed88190-00d0-4580-b938-25dac2ca75e3.png">
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/46792476/214376226-5fc972c7-2c1b-4cfd-9f81-4719a2947919.png">

**Desktop (please complete the following information):**
Latest FireFox

**Additional context**
Love your work. This is the best overall Dark theme for Rocket.Chat!

**Comment by pbaity** [comment]
@ddkedr Thanks for opening the issue! Glad to hear from you and I'm glad you enjoy the dark theme, though it's hardly my work - there are a lot of fantastic and talented contributors to this project that have made it great. 

I appreciate those screenshots, but to help me out, could you also list out their locations (e.g., Administration > Settings) along with specifically mentioning which elements have light borders? Of course I see them in your screenshots, but I want to make sure I find them all and fix them. (If you've found more than what's above, include both descriptions and screenshots for those too!)

Once we have a detailed list of borders that need to darkened for this issue, we can fix them specifically and solve this issue. (If you find more after that, you can open another issue.)

**Comment by chotaire** [comment]
@ddkedr Rocket.Chat 6.0.0 comes with its own official dark mode integrated and has this border issue fixed. So updating to Rocket.Chat 6.0 (and removing this rocketchat-dark-mode from your installation) would fix that issue for you.

If you are insisting to stay on a version lower than v6.0.0 (e.g. if you really need custom roles without an enterprise subscription), someone of us who hasn't updated yet might be willing to submit a patch?

**Comment by ddkedr** [comment]
Thank you, @pbaity for your effort, you're doing an amazing job. But I am in fact on enterprise version, so I'm going to update to version 6.0

**Comment by pbaity** [comment]
@ddkedr That's what I'd recommend as well. Thanks for using our dark theme though!
