### ISSUE TITLE
Poll App not compatible to Dark theme

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#29]
**Describe the bug**
There is a poll app https://github.com/sampaiodiego/rocket.chat.app-poll
And create a poll in Dark mode looks not so good

**To Reproduce**
1. Install https://github.com/sampaiodiego/rocket.chat.app-poll
2. Create vote

**Expected behavior**
All respect Dark mode

**Screenshots**
![image](https://user-images.githubusercontent.com/4023037/79554094-404dfa00-80a6-11ea-92fb-aae15ee0cd07.png)
As you can see - whole windows is white.
Header - not good
Drop down list - not good

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser 81
 - Version 2.17.9

**Comment by pbaity** [comment]
@ankar84 I think #30 may have fixed this issue. Can you confirm?

**Comment by ankar84** [comment]
> @ankar84 I think #30 may have fixed this issue. Can you confirm?

Hi, @pbaity 
Definitely fixed!
![image](https://user-images.githubusercontent.com/4023037/80477611-e75b4d00-8954-11ea-939e-4b3ddcdd607b.png)
Thanks!
