### ISSUE TITLE
Dark mode toggle not persistent between sessions

### ISSUE THREAD

**Issue by brittyazel** [pbaity/rocketchat-dark-mode#3]
I'm not sure if this can be fixed in the context of this mod, but each time I restart RocketChat I have to re-enable night mode. I.e. the setting isn't being saved between sessions. Any ideas?

Also, have you considered upstreaming this feature? I'd love to see this in the core release

**Comment by brittyazel** [comment]
Ok I fixed it, I needed to append this to the bottom of the javascript

```
// Apply dark mode immediately if it's been set previously
if(localStorage.getItem('dark-mode') === 'true') {
  document.body.classList.add('dark-mode');
}
```

**Comment by pbaity** [comment]
@brittyazel I think https://github.com/pbaity/rocketchat-dark-mode/pull/4 closes this, but reopen if you need to!
