### ISSUE TITLE
Directory search field bug

### ISSUE THREAD

**Issue by ankar84** [pbaity/rocketchat-dark-mode#32]
Version of RC 3.1.1
Directory search field text not contrast
![image](https://user-images.githubusercontent.com/4023037/80484764-efb98500-8960-11ea-996b-ac04fed42960.png)

Here is **test** search query
![image](https://user-images.githubusercontent.com/4023037/80484808-01029180-8961-11ea-8755-d086a436cbbb.png)

**Comment by ankar84** [comment]
**color: var(--color-dark);** in 
body.dark-mode .rcx-box * .rcx-input-box,
body.dark-mode .rcx-box * .rcx-select {
	**color: var(--color-dark);**
	background-color: var(--message-box-background);
}
fixed issue
![image](https://user-images.githubusercontent.com/4023037/80568561-ec290b00-89ff-11ea-8a68-27a817e5d3dc.png)

**Comment by henryfok** [comment]
```
body.dark-mode .rcx-box--text-style-h1, 
body.dark-mode .rcx-subtitle, 
body.dark-mode .rcx-box--text-color-default, 
body.dark-mode .rcx-box--text-color-info {
    color: var(--color-dark);
}
```
This makes all alot of the text on the directory page hard to read
![image](https://user-images.githubusercontent.com/9781557/80646929-7bdfb100-8a22-11ea-890b-b9ea406694d6.png)

**Comment by ankar84** [comment]
> ```
> body.dark-mode .rcx-box--text-style-h1, 
> body.dark-mode .rcx-subtitle, 
> body.dark-mode .rcx-box--text-color-default, 
> body.dark-mode .rcx-box--text-color-info {
>     color: var(--color-dark);
> }
> ```
> 
> This makes all alot of the text on the directory page hard to read
> ![image](https://user-images.githubusercontent.com/9781557/80646929-7bdfb100-8a22-11ea-890b-b9ea406694d6.png)

You right! Need more correct solution.

**Comment by pbaity** [comment]
@ankar84 Is this still an issue? I don't see it in 3.5.1 on Mac:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/39106297/90301458-f87d8a80-de6d-11ea-98af-076efe68cea1.png">
If not, let's close the issue since fewer and fewer people will be using these older versions.

**Comment by ankar84** [comment]
I think you are right!
It was fixed with some pr.
