### ISSUE TITLE
Register Account and Reset Password buttons hidden when on login page (perhaps due to dark mode default being set)

### ISSUE THREAD

**Issue by user88578** [pbaity/rocketchat-dark-mode#35]
**Describe the bug**
On the initial splash page/login page of rocketchat the Register and Reset password buttons are completely hidden. 

The buttons are still there and clickable but hidden as white on white.

**To Reproduce**
Installed the theme as advised on your readme and set (though don't know if this is the root cause, that is the only thing I changed):

`const darkModeDefault = true;
`

in `Custom Script for Logged In Users` section.

**Expected behavior**
Reset Password and Register New Account buttons visible like usual.

**Screenshots**

![invis_buttons](https://user-images.githubusercontent.com/64728539/80910718-49d39500-8d29-11ea-9f37-a89a5781a475.png)

**Desktop:**
It seems to not happen 100% of the time, though being visible seems to be the exception and most users make the complaint they could not see it and I have to instruct them on how to click the hidden Register button. I tried on both Firefox v75 and Chromium Version 81.0.4044.129 (Official Build) both on Arch Linux (64-bit) and not visible for me in either case.

One member said they could see it when signing up via desktop Mac on chrome.

Another user on Chrome on Windows could not see it.

**Smartphone (please complete the following information):**
Do not specific data on their devices but it is happening for most users and I know some of them are using mobile to sign up and one complained last night of the same issue.

**Additional context**
None.

**Comment by pbaity** [comment]
Thanks for reporting this @user88578 - I'm one of those people who can't reproduce the issue, or else I hopefully would've noticed this earlier. Applying dark mode to the login screen was requested in https://github.com/pbaity/rocketchat-dark-mode/pull/21 and I implemented in https://github.com/pbaity/rocketchat-dark-mode/pull/22, but what do you think of just reversing those changes and leaving the login screen unstyled? Seems like getting it to work consistently is more trouble than it's worth.

**Comment by user88578** [comment]
Hi, thanks for the reply :)

Yes definitely I have no problem at all with no style on the login page. It is causing havok for new members joining and I have to explain the reason for this thing being invisible and carefully go through how to get them to click the invisible button. They are thinking they are banned or it is disabled etc. :)

Just want a functioning sign up page, style is irrelevant for that page imo.

**Comment by pbaity** [comment]
@user88578 Try out the code in https://github.com/pbaity/rocketchat-dark-mode/pull/36 which contains all our updates but with login styles removed. Let me know if this fixes!

**Comment by user88578** [comment]
Yup, seems to work fine. 

Thanks :).

**Comment by pbaity** [comment]
@user88578 Seems that removing styles for the login page isn't an option, since it shares some classes that are affected by dark mode. I fixed in #38 if you'd be willing to confirm that stills works for you - if not, just comment on the PR so I can fix.
