### ISSUE TITLE
Login Page Doesn't Display Correctly When Dark Mode Is Enabled

### ISSUE THREAD

**Issue by hp734** [pbaity/rocketchat-dark-mode#37]
Login Page Doesn't Display Correctly When Dark Mode Is Enabled

If you turn on dark mode before logging in, the colors for the login page are messed up and look bad. It looks fine after login. It also looks fine before login if you haven't yet enabled dark mode.

**Comment by pbaity** [comment]
@hp734 I had tried in https://github.com/pbaity/rocketchat-dark-mode/pull/36 to remove styles for the login page, but it looks like there have to be rules in order to keep the login page clean. I opened https://github.com/pbaity/rocketchat-dark-mode/pull/38 to fix this, see what you think.

**Comment by 238bfd3** [comment]
Hey it looks great. I was the user above, but never remember my passwords to GitHub as I just make throwaway accounts using throwaway emails when I need to report a bug. Thanks for fixing. Please merge!!

**Comment by pbaity** [comment]
@hp734 / @238bfd3 🤣  allow me to suggest another project I've worked on, [LessPass](https://github.com/lesspass/lesspass). 

But I'll merge the PR now. Cheers!
