### ISSUE TITLE
colors for presence are not distinguishable

### ISSUE THREAD

**Issue by adipose** [pbaity/rocketchat-dark-mode#46]
![image](https://user-images.githubusercontent.com/3324395/89588193-055c0780-d7f8-11ea-876b-c97cdbf9bc09.png)

These colors don't work--i can't tell who is logged on or off!

**Comment by pbaity** [comment]
@adipose Heads up, I'm red-green colorblind, so forgive me if I say anything stupid 😅 

But I don't seem to have the issue with the online color being too dark. Here's what it looks like for me:
![image](https://user-images.githubusercontent.com/39106297/89780358-4a758780-dadf-11ea-8b90-085b1aebecb5.png)

With the change you added in #47, it looks like this for me:
![image](https://user-images.githubusercontent.com/39106297/89780382-582b0d00-dadf-11ea-9f1d-fd8ba5b5e510.png)

Can you give me the details of your Rocket.Chat instance? (I'm using 3.4.2 on Mac, both in the desktop app and Firefox.)

**Comment by adipose** [comment]
I am also a bit colorblind. Is that screenshot from the contact list?

I am on 3.5.1 which may explain the difference.

**Comment by pbaity** [comment]
Hm, odd. Our snap just got updated to 3.5.1 and I still don't see the issue of them being too dark...it looks about the same as it did previously in 3.4.2. But frankly, I like the green color you provided better, and this is a subtle and precise change, so I'm going to merge your PR anyway. If anybody finds takes issue with it they can let me know.

**Comment by adipose** [comment]
Thanks a lot for looking into this. I really don't know why it behaves this way for me. I have also overridden the busy color as it was also dark... I am assuming you don't see this issue on 3.5.1?

**Comment by pbaity** [comment]
Here's what I see on 3.5.1 (without your code change):
<img width="61" alt="image" src="https://user-images.githubusercontent.com/39106297/90168686-74db7500-dd6b-11ea-99e4-ec465c34a3a9.png">
Any chance you've got a conflicting style you or someone else has added?

**Comment by adipose** [comment]
This is embarrassing, but in my defense, it wasn't my fault.  I had reset all the custom "colors" I was using from an older theme.  When I just went back in, they were still set.  So I reset them again and saved them.  It still didn't work.  So I went to check again, and they were all there--again.  I did this about 10 times including restarting the server, clearing caches, etc.  Nothing worked.

In the send, I had to do:

col.remove({_id : /theme/})

On the rocketchat_settings collection.  Otherwise, those color entries stayed forever.  Now, your theme is working ok without my changes...sorry to waste your time!

**Comment by pbaity** [comment]
No worries, just glad you figured it out! Cheers!

**Comment by adipose** [comment]
Thanks again, theme is great!

**Comment by jasonsumner** [comment]
I pulled for the first time and had the same issue. Had issues with my github account, but I was going to post the same thing. There are some additional entries that can be made for the other status bubbles as well. 

`    --status-away: #fcb316;
    --status-busy: #f04747;
    --status-invisible: #bbb;`

**Comment by adipose** [comment]
Turns out those are unnecessary if you have no conflicting theme stuff.  But it seems rocketchat is broken somehow (maybe because I have been upgrading from much older versions for some time), and you can't update or clear all of them from the interface.
