### ISSUE TITLE
[DropDown List] - text not visible(fontcolor:black)

### ISSUE THREAD

**Issue by 6uhrmittag** [pbaity/rocketchat-dark-mode#48]
**Describe the bug**
The text in drop-down lists is not readable, because the fontcolor is the same as the "dark" color

I did saw it on 2 occoccasions, _file-types_ and _member filter_.

**To Reproduce**
1. Enable Darkmode
2. Open Chat or Channel
3. Choose _files_ top right
4. Click on _file-types box_ all to choose between all/videos etc.

**Expected behavior**
The text should be readable -> fontcolor: white

**Screenshots**
<img width="310" alt="2020-08-07 14_07_28-" src="https://user-images.githubusercontent.com/5658838/89644342-f9377f00-d8b7-11ea-8022-58bcdf8cb150.png">
<img width="313" alt="2020-08-07 14_07_50-Chat" src="https://user-images.githubusercontent.com/5658838/89644343-f9d01580-d8b7-11ea-88d9-f84d7f5956b6.png">

**Versions:**
- PC Client, Windows: 2.17.2
- Chrome, Windows: 84.0.4147.105 
- RocketChat Server: 3.4.2 (latest Snap)
- rocketchat-dark-mode: latest master 5410abb3232cb9160c369dfee60a23c992d77a08 (and previous)

**Comment by pbaity** [comment]
Unfortunately I don't have a Windows machine to troubleshoot this on. For me, on Mac and using 3.5.1 (now the latest snap) with the desktop app, Chrome, and FF, I see this:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/39106297/90175229-1adfad00-dd75-11ea-9ec4-ca5316aba5e3.png">
Looks like it's up to our community to solve this one 🙂

**Comment by brunobertoldi** [comment]
Same here using Linux Desktop:

![image](https://user-images.githubusercontent.com/19298197/90179843-76fdfd80-dd84-11ea-9d7b-f5f333d0aff1.png)

More context: The refactored UIs are ok, e.g. Administration Panel and User Profile

**Comment by pbaity** [comment]
When I've got the time I'll whip up a Linux VM and check it out, unless somebody beats me to it

**Comment by UncleSamMericaMan** [comment]
Hey guys! Submitted a Pull that should resolve this issue!
