### ISSUE TITLE
If you have E2E encryption enabled, its hard to close blue bar at the top since the X is invisible in dark mode

### ISSUE THREAD

**Issue by bj47cf** [pbaity/rocketchat-dark-mode#58]
If you have E2E encryption enabled, its difficult to close blue bar at the top because the X is invisible in dark mode.

Whenever you have E2E encryption enabled and first join a channel/server it will have a blue bar at the top of RocketChat reminding you to store your encryption key. Usually there is an X at the top right side you can click to close this. This X is invisible while dark mode is enabled. I can still close it because I know where X should be, but to new users not familiar with RocketChat this will be difficult to find for them. Please make the X visible again.

**Comment by pbaity** [comment]
@bj47cf I don't see this in light mode either:
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/39106297/92537086-48e7ce00-f209-11ea-8c03-4c48adbb8f38.png">

For me, once I click on the message, it gives me option to dismiss (here shown split in light and dark mode):
<img width="503" alt="image" src="https://user-images.githubusercontent.com/39106297/92536993-06be8c80-f209-11ea-9d29-70565fb06cf3.png">

**Comment by pbaity** [comment]
I don't think this is a bug, so I'm closing. If anyone disagrees just reopen or comment.
