### ISSUE TITLE
User presence status icon

### ISSUE THREAD

**Issue by scrivna** [pbaity/rocketchat-dark-mode#63]
**Describe the bug**
The user presence status icon color is overridden with the dark theme background color

**To Reproduce**
1. In RC > 3.5 click a users name in the channel window
2. Observe the user card that pops up

**Expected behavior**
The modal pop-up user card should have a colored presence status icon as it does in "light mode"

**Screenshots**
![Screenshot 2020-08-24 at 10 25 33](https://user-images.githubusercontent.com/53125/91076514-7ec76880-e5f4-11ea-8570-8ae1a38d6d7c.png)

**Additional context**

I've spent some time trying to target and fix this but have run out of ideas.

This is caused from the styles "body.dark-mode .rcx-box" which is used as a generic catch-all that catches a bunch of areas, i tried targeting the presence icon with a ":not()" selector but CSS doesn't support enough complexity to target this (as there's no class name on the presence icon). So I'm a bit stuck as to how to target it.

Overwriting the generic "body.dark-mode .rcx-box" class with more specific would be possible, but seems like it would require a lot of definitions.

Hoping someone smart here can think up a simpler solution!

**Comment by pbaity** [comment]
> Hoping someone smart here can think up a simpler solution!

Clearly I am not this person, I gave it a try with the same result. I don't want to start writing a thousand rules for every instance of the `rcx-box` class, so I'm going to 1) wait for someone smarter to show up, that's saved me a few times already, and 2) open an issue with RocketChat to ask politely if they can give that little element a class or ID of it's own so it can be targeted with custom CSS. In the particular case of status icons, that seems reasonable.

**Comment by pbaity** [comment]
It was hard to tell if I ought to open a bug or feature request for this one, since it wasn't really either, but I opened https://github.com/RocketChat/feature-requests/issues/389.

**Comment by pbaity** [comment]
This seems to now be resolved: 
![image](https://user-images.githubusercontent.com/39106297/104227444-675c1100-5417-11eb-877a-c17dd7b27e1c.png)
If anyone finds otherwise, they can reopen this issue.
