### ISSUE TITLE
Hover Menu is Transparent

### ISSUE THREAD

**Issue by iamjameswalters** [pbaity/rocketchat-dark-mode#67]
![image](https://user-images.githubusercontent.com/33947683/93928863-fa4a3180-fce8-11ea-950e-2402466ac274.png)

This hover menu for messages appears to be transparent now, should be opaque (with one of these gray colors).

I don't think it much matters with RocketChat, but this in on Firefox in Windows 10.

**Comment by pbaity** [comment]
I added code from #66 and that seemed to cause this issue on our server. I've removed that code and it should be fixed now.
