### ISSUE TITLE
Hovering over a message, white highlight box.

### ISSUE THREAD

**Issue by tripout** [pbaity/rocketchat-dark-mode#76]
**Describe the bug**
Hovering over a message shows a white highlight

**To Reproduce**
1. Go to 3.8.0-develop
2. Hover over a previous message
3. ????
4. Profit?

**Expected behavior**
Using the dark theme I would expect this to be dark themed as well.

**Screenshots**
https://imgur.com/YJB7i03

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86

**Additional context**
- Also happens on the electron desktop app

**Comment by pbaity** [comment]
@tripout I'm using the snap install which is at 3.6.2 and this doesn't occur. If by 3.8.0-develop you mean you're using a branch for development, I can't promise dark mode will work there as it continues to change. Can you give me some more information (links included) about that version? I don't see a 3.8.0-develop branch in the Rocket.Chat repo, but I'm probably looking in the wrong place.

**Comment by tripout** [comment]
Yes the docker-compose file I use pulls the latest develop image.

image: rocketchat/rocket.chat:develop

**Comment by tripout** [comment]
Looks like the latest fix you did a couple of days ago fixed the hover colors for 3.8.0-develop.  Thank you!
