### ISSUE TITLE
Sidebar top menu has poor spacing

### ISSUE THREAD

**Issue by pbaity** [pbaity/rocketchat-dark-mode#87]
**Describe the bug**
The buttons in the top menu of the sidebar for dark mode, home, search, etc. are pretty spread out weirdly (at least on smaller screens; haven't yet confirmed this is still happening on larger screens). 

**To Reproduce**
1. Take your eyes and put them on the top left corner of your screen when Rocket.Chat is open to the main chat.

**Expected behavior**
These buttons should be spaced better.

**Screenshots**
<img width="353" alt="image" src="https://user-images.githubusercontent.com/39106297/99978056-79082d00-2d73-11eb-86b8-0d2253dacf33.png">

**Comment by pbaity** [comment]
Adding this rule:
```css
aside.sidebar--main .rcx-sidebar-topbar .rcx-button--small-square {
    width: 1.35rem;
}
```
Seems to help at least on my screen:

<img width="293" alt="image" src="https://user-images.githubusercontent.com/39106297/99978213-a94fcb80-2d73-11eb-8cc9-3d563a9cf5aa.png">

I should be able to connect to a bigger screen later and confirm this works.

**Comment by mlongmiresqa** [comment]
Adding that rule fixed the issue for me as well. 3440x1440 monitor here.

![Screenshot 2020-12-07 110253](https://user-images.githubusercontent.com/8139065/101393555-23a44380-387c-11eb-94ba-103ee59249f9.png)

**Comment by pbaity** [comment]
This got added in #96 . Fixed now.
