### ISSUE TITLE
Dark Mode Toggle Button is gone in Rocket.Chat 3.9.0

### ISSUE THREAD

**Issue by Weuxel** [pbaity/rocketchat-dark-mode#92]
**Describe the bug**
Dark Mode Toggle Button is gone in Rocket.Chat 3.9.0

**To Reproduce**
1. Update to Rocket.Chat 3.9.0.
2. Toggle Button is gone.

**Expected behavior**
Toggle Button should appear in the UI.

**Screenshots**
<img width="272" alt="no_toogle_button" src="https://user-images.githubusercontent.com/1791989/100598071-86d32a80-32fe-11eb-8721-c29f475ed640.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 
 - Browser: Rocket.Chat Client 3.0.7, Safari 14.0

**Comment by rahul-arasikere** [comment]
Updating to the version on master fixed it for me (based on 3.8.0).

**Comment by Weuxel** [comment]
Confirmed. Thanks!
