### ISSUE TITLE
hljs-subst should be a light colour

### ISSUE THREAD

**Issue by notatallshaw** [pbaity/rocketchat-dark-mode#93]
Currently when you create a string substitution in the code syntax you get a very dark color, almost impossible to see. E.g. 

    ```python
    f_string = f'{this currently is unreadable in dark mode}`
    ```

The CSS class for this is "hljs-subst", I've tested it as white and it looks fine, maybe it would be nice as another light color.

**Comment by pbaity** [comment]
@notatallshaw So sorry for the delay, I was out for the holidays! Check out https://github.com/pbaity/rocketchat-dark-mode/pull/100 and let me know what you think. I'm not opposed to coloring them white, but figured I'd keep it the same color with other elements that it shares color with in light mode.

**Comment by notatallshaw** [comment]
No problem, this looks great to me!
