### ISSUE TITLE
Add option for light/dark in Room Actions toolbar

### ISSUE THREAD

**Issue by ninermac49** [pbaity/rocketchat-dark-mode#94]
I use rocket chat often with it's embedded layout. I would love to have the ability to toggle light/dark in the Room Actions as that is the only toolbar available in this mode.

**Comment by pbaity** [comment]
@ninermac49 That's a good idea. In a best-case scenario I think our JS could detect embedded mode and append the toggle button to the channel options instead of the sidebar. I'll start looking into if this is possible.

**Comment by jrgong420** [comment]
Digging out this one: We are using embedded view in our discourse forum and we disabled the menu bar. A dark/light toggle in the channel settings or maybe even via URL parameter would be great.

**Comment by pbaity** [comment]
This has been added in #163 by @TBG-FR.  For this to work, enable the top navbar in the embedded layout by going to "Administration -> Layout -> Interface -> Show top navbar in embedded layout". You'll now get the dark mode button in the top navbar.
