### ISSUE TITLE
the theme switch button is gone again in rc 3.10

### ISSUE THREAD

**Issue by awunder** [pbaity/rocketchat-dark-mode#97]
**Describe the bug**
the theme switch button is gone again in rc 3.10
**To Reproduce**
install rocket 3.10 and you see it right away

**Expected behavior**
it should be visible again

**Screenshots**
![image](https://user-images.githubusercontent.com/13486613/103337755-4e805280-4a4a-11eb-9231-1d5938dd74ce.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version unclear, its within ferdi

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by MNUser** [comment]
Fixed it for me by replacing
`const sidebarToolbar = $('.rcx-\\@vi4iz8').first();`
with
`const sidebarToolbar = $('.rcx-css-vi4iz8');`

although not sure if this is the proper way of doing this.

The icon is now a little bit too small.

**Comment by mrplow** [comment]
Thanks @MNUser, better than nothing for now

**Comment by nhcarrigan** [comment]
I can reproduce this issue on the Rocket.Chat desktop client, as well - and the fix above does work, with the slightly smaller icon.
The hover effect suggests the icon is the correct size, though, so the SVG might need resizing instead?

I would be happy to play with that a bit, if desired.

**Comment by awunder** [comment]
yeah, thx @MNUser 

rest was just a little css... change

```
.rcx-icon--name-darkmode {
  height: .9em;
}
```

to

```
.rcx-icon--name-darkmode {
	height: 1.35em;
}
```

and you're good to go

**Comment by antoine-roux** [comment]
> Fixed it for me by replacing
> `const sidebarToolbar = $('.rcx-\\@vi4iz8').first();`
> with
> `const sidebarToolbar = $('.rcx-css-vi4iz8');`
> 
> although not sure if this is the proper way of doing this.

IMHO the following should be more robust for future changes 😉.
```js
const sidebarToolbar = $('.rcx-sidebar-topbar .rcx-button-group').first();
```

My best for all of you!
Antoine

**Comment by pbaity** [comment]
@antoine-roux I've tested your suggestion and so far it looks good. If you open a PR for it, I'll merge it, and that way you can get credit for it! Or if you prefer I'll just add it.

I think all the issues described here are now fixed. If anyone finds otherwise, reopen this issue.
